export const FETCH_NEWS_DATA = "FETCH_NEWS_DATA"
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE"

export const FETCH_SINGLE_DATA = "FETCH_SINGLE_DATA"
export const FETCH_SINGLE_SUCCESS = "FETCH_SINGLE_SUCCESS"
export const FETCH_SINGLE_FAILURE = "FETCH_SINGLE_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const SEARCH_NEWS="SEARCH_NEWS"

export const POST_NEWS_DATA = "POST_NEWS_DATA"
export const POST_NEWS_SUCCESS = "POST_NEWS_SUCCESS"
export const POST_NEWS_FAILURE = "POST_NEWS_FAILURE"

export const POST_BOOK_DATA = "POST_BOOK_DATA"
export const POST_BOOK_SUCCESS = "POST_BOOK_SUCCESS"
export const POST_BOOK_FAILURE = "POST_BOOK_FAILURE"
