export const FETCH_NEWS_DATA = "FETCH_NEWS_DATA"
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS"
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const SEARCH_NEWS="SEARCH_NEWS"

